"""
apt_dat.py ported verbatim. Tests pin: nearest-airport-block matching over
a synthetic multi-airport apt.dat, the anonymize_visual_pavement row
surgery (surface->transparent, lights/auto-signs zeroed, beacon/signs/
painted-lines dropped, everything else preserved), boundary-ring bbox
extraction, and jetway-row stripping.
"""
import math
import tempfile
import unittest
from pathlib import Path

import apt_dat
import airport_layout


def _write_synthetic_apt_dat(path: Path):
    """Two airports, far enough apart that nearest-match is unambiguous.
    Airport reference lat/lon comes ONLY from "1302 datum_lat/datum_lon"
    rows (per _build_airport_index) -- the "1" header row itself only
    supplies the ICAO ident at parts[4], not coordinates."""
    lines = [
        "1200 Generated by test fixture",
        "",
        "1  100 0 0 AAAA Test Airport Alpha",
        "1302 datum_lat 47.505",
        "1302 datum_lon 8.505",
        "100 45.00 1 0 0.15 0 0 0 09 47.500000 8.500000 0.00 0.00 3 0 0 0 27 47.510000 8.510000 0.00 0.00 3 0 0 0",
        "18 47.505 8.505 3 400 1",
        "20 47.501 8.500 0 0 5 0 A1",
        "1500 47.502 8.501 0 90.0 12.0 1 GATE1",
        "1  50 0 0 BBBB Test Airport Bravo Far Away",
        "1302 datum_lat 10.000",
        "1302 datum_lon 100.000",
        "100 45.00 1 0 0.15 0 0 0 09 10.000000 100.000000 0.00 0.00 3 0 0 0",
        "99",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


class TestAptDat(unittest.TestCase):
    def test_find_nearest_airport_block_picks_closest(self):
        with tempfile.TemporaryDirectory() as td:
            apt_path = Path(td) / "apt.dat"
            _write_synthetic_apt_dat(apt_path)
            result = apt_dat.find_nearest_airport_block(apt_path, 47.505, 8.505)
            self.assertIsNotNone(result)
            block_lines, ident, distance_km = result
            self.assertEqual(ident, "AAAA")
            self.assertLess(distance_km, 1.0)
            self.assertTrue(any(line.startswith("100 ") for line in block_lines))

    def test_find_nearest_airport_block_too_far_returns_result_anyway(self):
        """find_nearest_airport_block itself doesn't apply the 15km cutoff
        -- that's main.py's own caller-side check on the returned distance.
        Confirm the distance is reported correctly so that caller-side gate
        works."""
        with tempfile.TemporaryDirectory() as td:
            apt_path = Path(td) / "apt.dat"
            _write_synthetic_apt_dat(apt_path)
            result = apt_dat.find_nearest_airport_block(apt_path, 10.0, 10.0)
            self.assertIsNotNone(result)
            _, _, distance_km = result
            self.assertGreater(distance_km, 15.0)

    _ANON_BLOCK = [
        "1  100 0 0 AAAA Test Airport",
        "100 45.00 1 1 0.15 1 2 1 09 47.500000 8.500000 0.00 60 3 2 1 1 27 47.510000 8.510000 0.00 60 3 2 1 1",
        "102 H 47.504 8.504 90.0 20.00 20.00 1 3 1 0.25 2",
        "110 1 0.15 0 taxiway_alpha",
        "111 47.502 8.502 3 102",
        "112 47.503 8.503 47.5031 8.5031 1 101",
        "18 47.505 8.505 3 400 1",
        "19 47.504 8.504 1",
        "20 47.501 8.500 0 0 5 0 A1",
        "21 47.507 8.507 0 3 2 VASI",
        "1500 47.5005 8.5005 0 90.0 12.0 1 GATE_A1",
        "120 taxi centerline",
        "111 47.500 8.500",
        "113 47.501 8.501",
        "115 47.502 8.502",
        "120 taxi lead-in LIT",
        "111 47.5000 8.5000 1 101",
        "111 47.5001 8.5001 1 101",
        "111 47.5002 8.5002 1",
        "14 47.505 8.505 0.0 0 Startup",
        "1204 1",
        "1302 windsock 47.506 8.506",
        "99",
    ]

    def test_anonymize_keeps_xplane_airport_lighting_by_default(self):
        """keep_lighting=True (the default): pavement, painted markings,
        beacon/windsock/signs and auto-jetways are still suppressed, but
        X-Plane's own runway edge/centreline/approach/TDZ/REIL lighting,
        PAPI (row 21) and taxiway edge lights (boundary-node light_type)
        are KEPT -- MSFS represents all of that procedurally, so the
        conversion never reproduces it."""
        out = apt_dat.anonymize_visual_pavement(self._ANON_BLOCK)
        out_text = "\n".join(out)

        self.assertNotIn("18 47.505", out_text)   # beacon dropped
        self.assertNotIn("19 47.504", out_text)   # windsock dropped
        self.assertNotIn("20 47.501", out_text)   # signs dropped
        self.assertNotIn("1500 47.5005", out_text)
        self.assertIn("21 47.507 8.507 0 3 2 VASI", out_text)   # PAPI KEPT

        # A purely-painted 120 linear feature + its nodes: still dropped.
        self.assertNotIn("120 taxi centerline", out_text)
        self.assertNotIn("111 47.500 8.500", out_text)
        # A 120 feature whose nodes carry LIGHT codes (>=100) -- taxiway
        # centre-line / lead-in lights -- is kept verbatim (MSFS renders
        # taxi lighting procedurally, so the conversion never reproduces
        # it; the thin painted stripe that rides along is the acceptable
        # cost).
        self.assertIn("120 taxi lead-in LIT", out_text)
        # kept feature, but each node's PAINT style is stripped -- only the
        # light code survives (in the first style slot).
        self.assertIn("111 47.5000 8.5000 101", out_text)
        self.assertNotIn("111 47.5000 8.5000 1 101", out_text)
        self.assertIn("111 47.5002 8.5002\n", out_text + "\n")   # paint-only node -> shape only
        self.assertNotIn("111 47.5002 8.5002 1", out_text)

        parts = next(l for l in out if l.startswith("100 ")).split()
        self.assertEqual(parts[2], "15")   # surface -> transparent
        self.assertEqual(parts[3], "0")    # shoulder off
        self.assertEqual(parts[5], "1")    # centreline lights KEPT
        self.assertEqual(parts[6], "2")    # edge lights KEPT
        self.assertEqual(parts[7], "0")    # auto distance signs off
        self.assertEqual(parts[13], "0", "end 1 markings zeroed")
        self.assertEqual(parts[14:17], ["2", "1", "1"], "end 1 apch/tdz/reil KEPT")
        self.assertEqual(parts[22], "0", "end 2 markings zeroed")
        self.assertEqual(parts[23:26], ["2", "1", "1"], "end 2 apch/tdz/reil KEPT")

        p102 = next(l for l in out if l.startswith("102 ")).split()
        self.assertEqual(p102[7], "15")
        self.assertEqual(p102[8], "0")     # markings off
        self.assertEqual(p102[11], "2")    # helipad edge lights KEPT

        self.assertEqual(next(l for l in out if l.startswith("110 ")).split()[1], "15")
        # 110-poly boundary node: keep the edge-LIGHT code, drop the
        # painted edge line (style 3 / 1) that rode with it -- otherwise
        # X-Plane repaints its default edge stripes over the converted
        # markings. `<coords> <lightcode>` is a valid source-native form.
        self.assertIn("111 47.502 8.502 102", out_text)
        self.assertNotIn("111 47.502 8.502 3 102", out_text)
        self.assertIn("112 47.503 8.503 47.5031 8.5031 101", out_text)
        self.assertNotIn("112 47.503 8.503 47.5031 8.5031 1 101", out_text)

        self.assertIn("14 47.505 8.505 0.0 0 Startup", out_text)
        self.assertIn("1302 windsock 47.506 8.506", out_text)

    def test_anonymize_can_still_strip_all_lighting(self):
        """keep_lighting=False: the old behaviour -- every runway/taxiway/
        approach light field zeroed and PAPI dropped, for a package that
        genuinely converts its own airport lighting."""
        out = apt_dat.anonymize_visual_pavement(self._ANON_BLOCK, keep_lighting=False)
        out_text = "\n".join(out)

        self.assertNotIn("21 47.507", out_text)   # PAPI dropped
        parts = next(l for l in out if l.startswith("100 ")).split()
        self.assertEqual(parts[5], "0")
        self.assertEqual(parts[6], "0")
        self.assertEqual(parts[13:17], ["0", "0", "0", "0"])
        self.assertEqual(parts[22:26], ["0", "0", "0", "0"])
        self.assertEqual(next(l for l in out if l.startswith("102 ")).split()[11], "0")
        self.assertIn("111 47.502 8.502\n", out_text + "\n")
        self.assertNotIn("111 47.502 8.502 3 102", out_text)
        # keep_lighting=False also strips the LIT 120 feature entirely.
        self.assertNotIn("120 taxi lead-in LIT", out_text)
        self.assertNotIn("111 47.5000 8.5000", out_text)

    def test_extract_boundary_ring_and_bbox(self):
        block = [
            "1  100 0 0 AAAA Test",
            "130 Airport Boundary",
            "111 47.500 8.500",
            "111 47.500 8.510",
            "113 47.510 8.510",
            "113 47.510 8.500",
            "100 45.00 1 0 0.15 0 0 0",  # unrelated row -- must stop collection here
        ]
        points = apt_dat.extract_boundary_ring(block)
        self.assertEqual(len(points), 4)
        bbox = apt_dat.boundary_bounding_box(points)
        self.assertIsNotNone(bbox)
        self.assertLess(bbox["west"], 8.500)
        self.assertGreater(bbox["east"], 8.510)
        self.assertLess(bbox["south"], 47.500)
        self.assertGreater(bbox["north"], 47.510)

    def test_boundary_bounding_box_empty_returns_none(self):
        self.assertIsNone(apt_dat.boundary_bounding_box([]))

    def test_strip_jetway_rows(self):
        block = ["1  100 0 0 AAAA Test", "1500 47.5 8.5 0 90.0 12.0 1 GATE1", "14 47.5 8.5 0.0 0 Startup"]
        out = apt_dat.strip_jetway_rows(block)
        self.assertFalse(any(l.startswith("1500") for l in out))
        self.assertTrue(any(l.startswith("14 ") for l in out))

    def test_bbox_is_near_accepts_a_nearby_candidate(self):
        # Two boxes both centered around real LHBP (Budapest), a few km
        # apart -- well within a real airport's own plausible footprint.
        trusted = {"west": 19.22, "south": 47.41, "east": 19.29, "north": 47.45}
        candidate = {"west": 19.21, "south": 47.40, "east": 19.30, "north": 47.46}
        self.assertTrue(apt_dat.bbox_is_near(candidate, trusted, max_km=15.0))

    def test_bbox_is_near_rejects_a_distant_candidate(self):
        # Confirmed real regression shape: placements_bbox correctly
        # centered on the real airport, but the other candidate (a
        # mismatched default-apt.dat match, or a bad single BGL reference
        # point) centered on a totally different, distant location -- must
        # be rejected rather than silently stretching a union bbox out to
        # cover the gap between them.
        trusted = {"west": 19.22, "south": 47.41, "east": 19.29, "north": 47.45}
        candidate = {"west": 21.00, "south": 45.00, "east": 21.05, "north": 45.05}
        self.assertFalse(apt_dat.bbox_is_near(candidate, trusted, max_km=15.0))

    def test_bbox_is_near_treats_either_missing_box_as_pass(self):
        box = {"west": 19.22, "south": 47.41, "east": 19.29, "north": 47.45}
        self.assertTrue(apt_dat.bbox_is_near(None, box, max_km=15.0))
        self.assertTrue(apt_dat.bbox_is_near(box, None, max_km=15.0))
        self.assertTrue(apt_dat.bbox_is_near(None, None, max_km=15.0))

    def test_write_apt_dat_produces_both_files(self):
        with tempfile.TemporaryDirectory() as td:
            out_path = Path(td) / "Earth nav data" / "apt.dat"
            block = ["1  100 0 0 AAAA Test", "1500 47.5 8.5 0 90.0 12.0 1 GATE1", "99"]
            apt_dat.write_apt_dat(out_path, block, source_note="matched AAAA")
            self.assertTrue(out_path.is_file())
            main_lines = out_path.read_text(encoding="utf-8").splitlines()
            # Header 1100 -- a 1200 header was not overriding the 1130 Global
            # Airports block; every working custom-airport pack ships 1000/1100.
            self.assertTrue(main_lines[1].startswith("1100"))
            # The airport NAME on row 1 is tagged so it's visible in X-Plane
            # which block actually won the override.
            row1 = next(l for l in main_lines if l.startswith("1 "))
            self.assertTrue(row1.rstrip().endswith("(msfs2xp)"))
            # anonymize_visual_pavement now drops auto-jetways from the main
            # file too (the package ships converted MSFS jetways), so neither
            # output carries row 1500.
            self.assertNotIn("1500 47.5 8.5", "\n".join(main_lines))

            xp11_path = out_path.with_name(out_path.name + ".xp11")
            self.assertTrue(xp11_path.is_file())
            xp11_lines = xp11_path.read_text(encoding="utf-8").splitlines()
            self.assertTrue(xp11_lines[1].startswith("1100"))
            self.assertNotIn("1500", "\n".join(xp11_lines))


class TestRepositionRunways(unittest.TestCase):
    _RWY_100 = ("100 45.00 1 1 0.15 1 2 1 09 47.500000 8.500000 0.00 60 3 2 1 1 "
                "27 47.510000 8.510000 0.00 60 3 2 1 1")

    def test_shifts_both_ends_by_the_same_delta_preserving_other_fields(self):
        # Native center is 0.001 deg north/east of the stock center
        # (47.505, 8.505) -- both ends should move by exactly that delta,
        # every other field untouched.
        native_center = (47.506, 8.506)
        out = apt_dat.reposition_runways([self._RWY_100], [native_center])
        parts = out[0].split()
        self.assertAlmostEqual(float(parts[9]), 47.501000, places=5)
        self.assertAlmostEqual(float(parts[10]), 8.501000, places=5)
        self.assertAlmostEqual(float(parts[18]), 47.511000, places=5)
        self.assertAlmostEqual(float(parts[19]), 8.511000, places=5)
        # width/surface/shoulder/smoothness/lighting/markings/etc untouched.
        self.assertEqual(parts[1:9], self._RWY_100.split()[1:9])
        self.assertEqual(parts[11:18], self._RWY_100.split()[11:18])
        self.assertEqual(parts[20:], self._RWY_100.split()[20:])

    def test_no_native_centers_leaves_block_untouched(self):
        out = apt_dat.reposition_runways([self._RWY_100], [])
        self.assertEqual(out, [self._RWY_100])

    def test_matches_each_native_center_to_nearest_stock_runway_once(self):
        rwy_a = "100 45.00 1 1 0.15 1 2 1 09 47.500000 8.500000 0.00 60 3 2 1 1 27 47.510000 8.510000 0.00 60 3 2 1 1"
        rwy_b = "100 45.00 1 1 0.15 1 2 1 13 10.000000 20.000000 0.00 60 3 2 1 1 31 10.010000 20.010000 0.00 60 3 2 1 1"
        native = [(10.0005, 20.0005), (47.5051, 8.5051)]  # deliberately out of order
        out = apt_dat.reposition_runways([rwy_a, rwy_b], native)
        parts_a, parts_b = out[0].split(), out[1].split()
        # rwy_a's stock center (47.505, 8.505) must match the SECOND native
        # center (47.5051, 8.5051), not the first (near rwy_b's location).
        self.assertAlmostEqual(float(parts_a[9]), 47.500100, places=4)
        self.assertAlmostEqual(float(parts_b[9]), 9.995500, places=4)


class TestReplaceTaxiNetworkAndStarts(unittest.TestCase):
    def test_no_layout_data_leaves_block_untouched(self):
        block = ["1200 old header", "1201 1 2 both 0 n0", "99"]
        layout = airport_layout.AirportLayout()
        out = apt_dat.replace_taxi_network_and_starts(block, layout)
        self.assertEqual(out, block)

    def test_strips_stock_network_and_starts_then_appends_native(self):
        block = [
            "1  100 0 0 AAAA Test",
            "1200 stock header",
            "1201 47.1 8.1 both 0 n0",
            "1202 0 1 twoway taxi_A",
            "1204 departure 09,27",
            "1206 0 1 twoway",
            "1300 47.2 8.2 90.0 gate all Stock Gate",
            "1301 D airline",
            "1400 47.3 8.3 0 Old Start",
            "99",
        ]
        layout = airport_layout.AirportLayout(
            taxi_nodes=[(47.43, 19.25), (47.431, 19.251)],
            taxi_edges=[(0, 1)],
            ramp_starts=[(47.44, 19.26)],
        )
        out = apt_dat.replace_taxi_network_and_starts(block, layout, airport_name="LHBP")
        out_text = "\n".join(out)

        # every stock network/start row is gone -- 1206 specifically:
        # confirmed real bug, it references 1201 node IDs exactly like
        # 1202 does, and got left dangling into the renumbered native
        # node space when this test was first written without it.
        for gone in ("1200 stock header", "1201 47.1", "1202 0 1 twoway taxi_A",
                     "1204 departure", "1206 0 1 twoway", "1300 47.2",
                     "1301 D airline", "1400 47.3"):
            self.assertNotIn(gone, out_text)
        # non-network rows are preserved
        self.assertIn("1  100 0 0 AAAA Test", out_text)
        self.assertIn("99", out_text)

        self.assertIn("1200 LHBP", out_text)
        self.assertIn("1201 47.43000000 19.25000000 both 0 n0", out_text)
        self.assertIn("1201 47.43100000 19.25100000 both 1 n1", out_text)
        self.assertIn("1202 0 1 twoway taxiway_F", out_text)
        self.assertIn("1300 47.44000000 19.26000000 0.00 misc all Start 1", out_text)

    def test_taxi_nodes_without_edges_still_emits_header_and_nodes(self):
        layout = airport_layout.AirportLayout(taxi_nodes=[(47.43, 19.25)])
        out = apt_dat.replace_taxi_network_and_starts(["99"], layout)
        out_text = "\n".join(out)
        self.assertIn("1200", out_text)
        self.assertIn("1201 47.43000000 19.25000000 both 0 n0", out_text)

    def test_truck_only_edge_is_reanchored_onto_the_new_node_numbering(self):
        """1206 ground-service-vehicle edges have no native BGL decode, so
        they can't be rebuilt -- but dropping them outright (an earlier
        version of this fix) silently breaks X-Plane's own ground-service
        AI (fuel trucks etc) at this airport, since 1206 is its only
        source of truck-specific routing. The real fix: re-anchor the
        stock block's own edge onto whichever NEW native node sits
        closest to each of its stock endpoints."""
        block = [
            "1201 47.43000100 19.25000100 both s0 sn0",
            "1201 47.43100100 19.25100100 both s1 sn1",
            "1206 s0 s1 twoway",
            "99",
        ]
        layout = airport_layout.AirportLayout(
            taxi_nodes=[(47.43, 19.25), (47.431, 19.251)],
            taxi_edges=[(0, 1)],
        )
        out = apt_dat.replace_taxi_network_and_starts(block, layout, airport_name="LHBP")
        out_text = "\n".join(out)
        self.assertIn("1206 0 1 twoway", out_text)

    def test_truck_only_edge_with_no_nearby_native_node_is_dropped(self):
        """A stock truck edge whose endpoint has no native node within
        _MAX_TRUCK_NODE_MATCH_M (e.g. a real truck route through part of
        the airport this rebuild dropped or relocated) must be left out
        entirely rather than guessed at."""
        block = [
            "1201 47.10000000 8.10000000 both s0 sn0",  # far from any native node
            "1201 47.43100100 19.25100100 both s1 sn1",
            "1206 s0 s1 twoway",
            "99",
        ]
        layout = airport_layout.AirportLayout(
            taxi_nodes=[(47.43, 19.25), (47.431, 19.251)],
            taxi_edges=[(0, 1)],
        )
        out = apt_dat.replace_taxi_network_and_starts(block, layout, airport_name="LHBP")
        self.assertFalse(any(line.startswith("1206") for line in out))

    def test_ramp_start_borrows_the_closest_stock_stands_heading_and_name(self):
        """Neither heading nor a display name has a confirmed BGL decode
        (see airport_layout.py) -- rather than a meaningless 0.0/"Start
        N", a native start close to a real stock stand should read AS
        that stand, positionally unchanged (the native lat/lon, not the
        stock one, per this function's own docstring)."""
        block = [
            "1300 47.43080000 19.25995000 42.61 gate jets|turboprops Gate 31",
            "1301 D airline",
            "1300 47.43107000 19.25951000 42.35 gate jets|turboprops Gate 32",
            "1301 D airline",
            "99",
        ]
        layout = airport_layout.AirportLayout(
            # ~1.5m from each stand's own stock position (a custom
            # rebuild), and ~44m from the OTHER stand -- unambiguously
            # closest to its own, well within _MAX_STAND_MATCH_M.
            ramp_starts=[(47.43081000, 19.25996000), (47.43108000, 19.25950000)],
        )
        out = apt_dat.replace_taxi_network_and_starts(block, layout)
        out_text = "\n".join(out)

        # Native positions preserved exactly; heading/name borrowed from
        # whichever stock stand is closest (first native start is nearest
        # to "Gate 31", second to "Gate 32" -- confirms a real nearest-
        # match, not just "always the first stock row").
        self.assertIn("1300 47.43081000 19.25996000 42.61 misc all Gate 31", out_text)
        self.assertIn("1300 47.43108000 19.25950000 42.35 misc all Gate 32", out_text)

    def test_ramp_start_falls_back_to_placeholder_when_no_stock_stand_is_close(self):
        block = ["1300 10.0 20.0 90.0 gate all Far Away Gate", "99"]
        layout = airport_layout.AirportLayout(ramp_starts=[(47.4310800, 19.2595500)])
        out = apt_dat.replace_taxi_network_and_starts(block, layout)
        out_text = "\n".join(out)
        self.assertIn("1300 47.43108000 19.25955000 0.00 misc all Start 1", out_text)

    def test_ramp_start_matching_consumes_each_stock_stand_at_most_once(self):
        """Two native starts both nearest to the SAME stock stand must not
        both borrow it -- confirms the greedy match removes a stand once
        used, same one-to-one philosophy as reposition_runways."""
        block = ["1300 47.4310800 19.2595500 42.61 gate jets Gate 31", "99"]
        layout = airport_layout.AirportLayout(
            ramp_starts=[(47.4310800, 19.2595500), (47.4310805, 19.2595505)])
        out = apt_dat.replace_taxi_network_and_starts(block, layout)
        out_text = "\n".join(out)
        self.assertEqual(out_text.count("Gate 31"), 1, "the stock stand must only be borrowed once")
        self.assertIn("Start 2", out_text, "the second, unmatched native start must fall back to the placeholder")


if __name__ == "__main__":
    unittest.main()
